### ISSUE TITLE
No module named 'unilm.data.bert_mlm_loader'

### ISSUE THREAD

**Issue by YijuGuo** [xy980523/MoEc_model#1]
Description:
I am trying to run some code and I am running into the following error:

`ModuleNotFoundError: No module named 'unilm.data.bert_mlm_loader'`

I checked the unilm/data/ directory and there is no bert_mlm_loader file present. Can someone please help me with this issue?

Expected behavior:
The script should run without any errors.

Actual behavior:
I encounter the error ModuleNotFoundError: No module named 'unilm.data.bert_mlm_loader'

**Comment by YuanX9** [comment]
Dear Guo:
Thank you for your attention. This repo currently only supports ''--task translation'', not ''--task pretraining''. The code related to pretraining will not be open source. You can use our code for machine translation as demonstrated in the readme.

**Comment by YijuGuo** [comment]
Thank you very much for your answer.

I am trying to understand the implementation of the MOE model in your code, and I noticed that there are two types of MOE layers: "gdmoe" and "tmoe". However, I could not find any information about the difference between them in your paper or documentation.

Could you please provide some insights into the differences between these two types of MOE layers and which papers they correspond to? I would greatly appreciate any information you can share.

Thank you for your help.

**Comment by YuanX9** [comment]
Dear Guo:
Please use "gdmoe" as depicted in "--arch" in readme.md.
"tmoe" is the code implementation for "x-moe" (arXiv preprint arXiv:2204.09179) that serves as the strong baseline in our paper.

**Comment by YijuGuo** [comment]
I successfully ran “gdmoe” according to the README file, but I'm curious to know which MOE baseline it is using. Could you please provide this information or point me to the relevant documentation?
Thank you!

**Comment by YuanX9** [comment]
Dear Guo:
"gdmoe" is the code implementation of "MoEc" proposed in our paper.
I'm sorry that it has caused you any confusion.

**Comment by YijuGuo** [comment]
Thank you very much for your quick and detailed reply. I benefited a lot from reading your paper～
