### ISSUE TITLE
Code hangs at generate_moe..py dist.init_process_group() during inference

### ISSUE THREAD

**Issue by YijuGuo** [xy980523/MoEc_model#2]
I am running inference using the script provided in the readme.md file, and the code seems to be getting stuck at the dist.init_process_group() function. 

I am using a single A100 GPU to run the code.

Here is the relevant code snippet:

```
import torch.distributed as dist
import random
port = random.randint(10000, 20000)
distributed_backend = 'nccl'
distributed_init_method = "tcp://localhost:{port}".format(port=port)

dist.init_process_group(
    backend=distributed_backend,
    init_method=distributed_init_method,
    world_size=1,
    rank=0,
)
```
I have verified that the port variable is being set correctly, and I am not seeing any error messages. However, the code just seems to hang at this point and never progresses.

Can you suggest any potential causes for this issue, or any steps I can take to debug the problem? Any help would be greatly appreciated.

**Comment by YuanX9** [comment]
Dear Guo:
I do not encounter this problem when running the code. This may be related to your environment. You may refer to this answer: https://stackoverflow.com/questions/66498045/how-to-solve-dist-init-process-group-from-hanging-or-deadlocks

**Comment by YijuGuo** [comment]
Hello, after I commented out `init_method=distributed_init_method`, I was able to run inference successfully. I wonder if it is caused by the limitation of the school server.
